name: Build
on:
  push:
    branches:
      - master
  pull_request:
  
jobs:          
  build:
    name: Dependencies
    runs-on: ubuntu-latest 
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Dependencies
        run: |
          go get github.com/fatih/color
          go get github.com/projectdiscovery/gologger

      - name: Build
        run: go build .
        working-directory: ./